#!/bin/bash
#
# Perform necessary netuitive setup steps
# after package is installed.
#

PROGNAME=$(basename $0)

function error_exit
{
  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
  exit 1
}

notify()
{
  echo "netuitive-agent: $1"
}

print_welcome()
{
  notify
  notify "Thank you for installing Netuitive's Agent!"
  notify
  notify "Please add your API key to the [[NetuitiveHandler]] section of the"
  notify "/opt/netuitive-agent/conf/netuitive-agent.conf"
  notify "file before restarting the service."
  notify
}


init_scripts()
{
  if [ -f "/bin/systemctl" ]; then
    mkdir -p /usr/lib/systemd/system
    cp /opt/netuitive-agent/netuitive/systemd/netuitive-agent.service /usr/lib/systemd/system/netuitive-agent.service
    /bin/systemctl daemon-reload
    sleep 2
    /bin/systemctl enable netuitive-agent.service
    # /bin/systemctl start netuitive-agent


  elif [ -f "/etc/redhat-release" -o -f "/etc/fedora-release" -o -f "/etc/system-release" ]; then
    cp /opt/netuitive-agent/netuitive/init.d/netuitive-agent /etc/init.d/netuitive-agent
    /sbin/chkconfig --add netuitive-agent
    /sbin/chkconfig netuitive-agent on
    # /sbin/service netuitive-agent start

  elif [ -f "/sbin/initctl" ]; then
    cp /opt/netuitive-agent/netuitive/upstart/netuitive-agent.conf /etc/init/netuitive-agent.conf
    # /sbin/initctl start netuitive-agent


  fi
}


case "$1" in
  2)
    # Looks like an RPM upgrade
    exit 0
    ;;

  configure)
    # Looks like a DEB install. We don't know if it is a fresh install or an
    # upgrade.
    if [ -z $2 ];
      init_scripts
    fi
    ;;

  *)
    if [ -x /bin/rpm ] ; then
        init_scripts
    fi
    ;;
esac

print_welcome

exit 0
