#!/bin/bash
#
# Perform necessary netuitive removal steps
# after package is uninstalled.
#

cleanup () {

    if [ -f "/usr/lib/systemd/system/netuitive-agent.service" ]; then
            /bin/systemctl disenable netuitive-agent.service
            rm -f /usr/lib/systemd/system/netuitive-agent.service
            /bin/systemctl daemon-reload
    fi

    if [ -f "/etc/init/netuitive-agent.conf" ]; then
            rm -f /etc/init/netuitive-agent.conf
    fi

    if [ -f "/etc/init.d/netuitive-agent" ]; then
            /etc/init.d/netuitive-agent stop
            rm -f /etc/init.d/netuitive-agent
    fi

    if [ -d "/opt/netuitive-agent" ]; then
            rm -rf /opt/netuitive-agent
    fi

    echo "The Netuitive agent has been uninstalled!"

}

if [ ! -f /etc/redhat-release -a ! -f /etc/fedora-release -a ! -f /etc/system-release ]; then
    if [ "$1" = "remove" ]; then
      cleanup
    fi
elif [ "x$1" = "x0" ]; then
  # RPM-based system and we're deinstalling rather than upgrading
  cleanup
fi



exit 0
