#!/bin/bash
#
# Perform necessary netuitive removal steps
# after package is uninstalled.
#

notify()
{
  echo "netuitive-agent remove: $1"
}

cleanup () {

  if [ -f "/usr/lib/systemd/system/netuitive-agent.service" ]; then
    /bin/systemctl disenable netuitive-agent.service > /dev/null 2>&1
    /bin/systemctl disable netuitive-agent.service > /dev/null 2>&1

    rm -f /usr/lib/systemd/system/netuitive-agent.service
    /bin/systemctl daemon-reload
  fi

  if [ -f "/etc/init/netuitive-agent.conf" ]; then
    rm -f /etc/init/netuitive-agent.conf
  fi

  if [ -f "/etc/init.d/netuitive-agent" ]; then
    /sbin/chkconfig netuitive-agent off
    rm -f /etc/init.d/netuitive-agent
  fi

  if [ -d "/opt/netuitive-agent" ]; then
    rm -rf /opt/netuitive-agent
  fi

  notify "The Netuitive agent has been removed!"

}

case "$1" in
  0)
    # Looks like an RPM remove
    cleanup
    ;;

  remove)
    # Looks like a DEB remove
    cleanup
    ;;

  *)
    # This is not a remove, nothing to do.
    ;;
esac



exit 0
