#!/bin/bash
#
# Perform necessary netuitive setup steps
# after package is installed.
#

PROGNAME=$(basename $0)

function error_exit
{
  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
  exit 1
}

notify()
{
  echo "netuitive-agent: $1"
}

print_welcome()
{
  notify
  notify "Thank you for installing Netuitive's Agent!"
  notify
  notify "Please add your API key to the [[NetuitiveHandler]] section of the"
  notify "/opt/netuitive-agent/conf/netuitive-agent.conf"
  notify "file before restarting the service."
  notify
}

cleanup_old_files()
{
  if [ -d "/opt/netuitive-agent/netuitive" ]; then
    rm -rf /opt/netuitive-agent/netuitive
  fi

}

init_scripts()
{


  if [ -f "/bin/systemctl" ]; then

    if [ -f "/usr/lib/systemd/system/netuitive-agent.service" ]; then
      notify "Updating startup script..."
      /bin/systemctl stop netuitive-agent
    fi

    mkdir -p /usr/lib/systemd/system
    cp /opt/netuitive-agent/.install/systemd/netuitive-agent.service /usr/lib/systemd/system/netuitive-agent.service
    /bin/systemctl daemon-reload
    sleep 2
    /bin/systemctl enable netuitive-agent.service
    # /bin/systemctl start netuitive-agent


  elif [ -f "/etc/redhat-release" -o -f "/etc/fedora-release" -o -f "/etc/system-release" ]; then

    if [ -f "/etc/init.d/netuitive-agent" ]; then
      notify "Updating startup script..."
      /sbin/service netuitive-agent stop
    fi

    cp /opt/netuitive-agent/.install/init.d/netuitive-agent /etc/init.d/netuitive-agent
    /sbin/chkconfig --add netuitive-agent
    /sbin/chkconfig netuitive-agent on
    # /sbin/service netuitive-agent start

  elif [ -f "/sbin/initctl" ]; then

    if [ -f "/etc/init/netuitive-agent.conf" ]; then
      notify "Updating startup script..."
      /sbin/initctl stop netuitive-agent
    fi

    cp /opt/netuitive-agent/.install/upstart/netuitive-agent.conf /etc/init/netuitive-agent.conf
    # /sbin/initctl start netuitive-agent

  elif [ `lsb_release -c -s` == "wheezy" ]; then

    if [ -f "/etc/init.d/netuitive-agent" ]; then
      notify "Updating startup script..."
      /sbin/service netuitive-agent stop
    fi

    cp /opt/netuitive-agent/.install/init.d/netuitive-agent-lsb /etc/init.d/netuitive-agent
    update-rc.d netuitive-agent defaults
    # /sbin/service netuitive-agent start
    # wheezy_notice

  fi
}

wheezy_notice()
{
  notify
  notify
  notify "The Netuitive agent requires a newer version of GLIBC than is installed by default on Debian 7 (Wheezy)."
  notify "Please refer to our on-line documentation for further installation instructions."
  notify
}

case "$1" in
  [2-9])
    # Looks like an RPM upgrade
    init_scripts
    exit 0
    ;;

  configure)
    # Looks like a DEB install. We don't know if it is a fresh install or an
    # upgrade.
    if [ -z $2 ]; then
      init_scripts
    fi
    ;;

  *)
    if [ -x /bin/rpm ] ; then
        init_scripts
    fi
    ;;
esac

cleanup_old_files
print_welcome

exit 0
