#!/bin/bash
#
# Perform necessary netuitive setup steps
# before package is installed.
#

upgrade()
{
  notify
  notify
  notify "Please remember to update your config file and restart the service after the upgrade completes"
  notify
  notify

}

notify()
{
  echo "netuitive-agent pre-upgrade: $1"
}

case "$1" in
  2)
    # Looks like an RPM upgrade
    upgrade
    ;;

  upgrade)
    # Looks like a DEB upgrade
    upgrade
    ;;

  *)
    # This is not an upgrade, nothing to do.
    ;;

esac