#!/bin/bash
#
# Perform necessary netuitive setup steps
# before package is installed.
#

upgrade()
{
#  NOW=$(date +"%s")
#  notify "Backing up /opt/netuitive-agent/conf/netuitive-agent.conf to /opt/netuitive-agent/conf/netuitive-agent.conf.${NOW}"
#  cp /opt/netuitive-agent/conf/netuitive-agent.conf /opt/netuitive-agent/conf/netuitive-agent.conf.${NOW}
  notify
  notify
  notify "Please remember to restart the service after the upgrade completes"
  notify
  notify

}

notify()
{
  echo "netuitive-agent pre-upgrade: $1"
}

case "$1" in
  2)
    # Looks like an RPM upgrade
    upgrade
    ;;

  upgrade)
    # Looks like a DEB upgrade
    upgrade
    ;;

  *)
    # This is not an upgrade, nothing to do.
    ;;

esac