#!/bin/bash
#
# Perform necessary netuitive setup steps
# prior to installing package.
#

PROGNAME=$(basename $0)

function error_exit
{
  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
  exit 1
}


if [ -f "/usr/lib/systemd/system/netuitive-agent.service" ]; then
  /bin/systemctl stop netuitive-agent
fi

if [ -f "/etc/init/netuitive-agent.conf" ]; then
  /sbin/initctl stop netuitive-agent
fi

if [ -f "/etc/init.d/netuitive-agent" ]; then
  /sbin/service netuitive-agent stop
fi


exit 0
