Vagrant.configure(2) do |config|

#  config.vbguest.auto_update = false

  config.vm.provider :virtualbox do |vb|
    vb.customize [
      "modifyvm", :id,
      "--memory", "1024",
      "--cpus", "1"
    ]
  end

  config.vm.define "centos6-test", primary: true do |c|
    c.vm.hostname = "centos6"
    c.vm.box = "bento/centos-6.7"
    c.vm.provision "shell", inline: "nohup python /vagrant/testserver.py  > /vagrant/testserver-`hostname -s`.out 2>&1 &"
    c.vm.provision "shell", inline: "for f in /vagrant/dist/*.rpm; do rpm -ivh $f; done"
    c.vm.provision "shell", inline: "cat /vagrant/test.conf > /opt/netuitive-agent/conf/netuitive-agent.conf"
    c.vm.provision "shell", inline: "service netuitive-agent start"
  end

  config.vm.define "centos7-test", autostart: false do |c|
    c.vm.hostname = "centos7"
    c.vm.box = "bento/centos-7.1"
    c.vm.provision "shell", inline: "nohup python /vagrant/testserver.py  > /vagrant/testserver-`hostname -s`.out 2>&1 &"
    c.vm.provision "shell", inline: "for f in /vagrant/dist/*.rpm; do rpm -ivh $f; done"
    c.vm.provision "shell", inline: "cat /vagrant/test.conf > /opt/netuitive-agent/conf/netuitive-agent.conf"
    c.vm.provision "shell", inline: "service netuitive-agent start"
  end

  config.vm.define "debian7-test", autostart: false do |c|
    c.vm.hostname = "debian7"
    c.vm.box = "bento/debian-7.9"
    c.vm.provision "shell", inline: "nohup python /vagrant/testserver.py  > /vagrant/testserver-`hostname -s`.out 2>&1 &"
    c.vm.provision "shell", inline: "apt-get update"
    c.vm.provision "shell", inline: "echo 'deb http://ftp.debian.org/debian experimental main' >> /etc/apt/sources.list"
    c.vm.provision "shell", inline: "apt-get update"
    c.vm.provision "shell", inline: "export DEBIAN_FRONTEND=noninteractive; apt-get -y -t experimental install libc6 libc6-dev libc6-dbg; sync; sync"
    c.vm.provision "shell", inline: "for f in /vagrant/dist/*.deb; do dpkg -i $f; done"
    c.vm.provision "shell", inline: "cat /vagrant/test.conf > /opt/netuitive-agent/conf/netuitive-agent.conf"
    c.vm.provision "shell", inline: "service netuitive-agent start"
  end


  config.vm.define "debian8-test", autostart: false do |c|
    c.vm.hostname = "debian8"
    c.vm.box = "bento/debian-8.2"
    c.vm.provision "shell", inline: "nohup python /vagrant/testserver.py  > /vagrant/testserver-`hostname -s`.out 2>&1 &"
    c.vm.provision "shell", inline: "for f in /vagrant/dist/*.deb; do dpkg -i $f; done"
    c.vm.provision "shell", inline: "cat /vagrant/test.conf > /opt/netuitive-agent/conf/netuitive-agent.conf"
    c.vm.provision "shell", inline: "/bin/systemctl start netuitive-agent"
  end

  config.vm.define "ubuntu12-test", autostart: false do |c|
    c.vm.hostname = "ubuntu12"
    c.vm.box = "bento/ubuntu-12.04"
    c.vm.provision "shell", inline: "nohup python /vagrant/testserver.py  > /vagrant/testserver-`hostname -s`.out 2>&1 &"
    c.vm.provision "shell", inline: "for f in /vagrant/dist/*.deb; do dpkg -i $f; done"
    c.vm.provision "shell", inline: "cat /vagrant/test.conf > /opt/netuitive-agent/conf/netuitive-agent.conf"
    c.vm.provision "shell", inline: "/sbin/initctl start netuitive-agent"
  end

  config.vm.define "ubuntu14-test", autostart: false do |c|
    c.vm.hostname = "ubuntu14"
    c.vm.box = "bento/ubuntu-14.04"
    c.vm.provision "shell", inline: "nohup python /vagrant/testserver.py  > /vagrant/testserver-`hostname -s`.out 2>&1 &"
    c.vm.provision "shell", inline: "for f in /vagrant/dist/*.deb; do dpkg -i $f; done"
    c.vm.provision "shell", inline: "cat /vagrant/test.conf > /opt/netuitive-agent/conf/netuitive-agent.conf"
    c.vm.provision "shell", inline: "/sbin/initctl start netuitive-agent"
  end

  config.vm.define "ubuntu15-test", autostart: false do |c|
    c.vm.box = "bento/ubuntu-15.04"
    c.vm.hostname = "ubuntu15"
    c.vm.provision "shell", inline: "nohup python /vagrant/testserver.py  > /vagrant/testserver-`hostname -s`.out 2>&1 &"
    c.vm.provision "shell", inline: "for f in /vagrant/dist/*.deb; do dpkg -i $f; done"
    c.vm.provision "shell", inline: "cat /vagrant/test.conf > /opt/netuitive-agent/conf/netuitive-agent.conf"
    c.vm.provision "shell", inline: "/bin/systemctl start netuitive-agent"
  end

end